name: ptm_pred
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  # Base Python
  - python=3.9

  # PyTorch & CUDA (GPU support)
  - pytorch
  - pytorch-cuda=11.8 
  - torchaudio
  - torchvision

  # Data Manipulation
  - pandas
  - numpy

  # Visualization
  - matplotlib

  # Utilities (Optional but highly recommended for ML metrics)
  - scikit-learn
  - tqdm

  # Pip specific packages (if any)
  - pip