name: ptm_pred
channels:
  - defaults
dependencies:
  # Base Python
  - python=3.9

  # Common Libraries
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - tqdm
  - biopython
  - pip  

  - pip:
    - torch --index-url https://download.pytorch.org/whl/cu118
    - torchvision --index-url https://download.pytorch.org/whl/cu118
    - torchaudio --index-url https://download.pytorch.org/whl/cu118